[package]
name = "homophones"
version = "0.2.0"
edition = "2021"
license = "BlueOak-1.0.0"

[dependencies]
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
scraper = "0.16.0"
# select = "*"
select = "0.6.0"
clap = { version = "4.2.2", features = ["derive"] }
