[package]
name = "homophones"
version = "0.2.1"
edition = "2021"
license = "BlueOak-1.0.0"

[dependencies]
reqwest = { version = "0.11.17", features = ["blocking", "json"] }
scraper = "0.16.0"
select = "0.6.0"
clap = { version = "4.2.2", features = ["derive"] }
